version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: my-secure-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes

volumes:
  redis-data:
